"""Email-style digest generation.

Builds a subject/body pair from an alert report so a future email channel can
send it. This module does NOT send email and contacts no external service.
"""

from __future__ import annotations

from datetime import date as _date

HEADER_NOTE = "Generated by Biotech Risk Scout. Diligence triage only, not investment advice."


def build_email_digest(
    report_text: str,
    subject_prefix: str = "Biotech Risk Scout",
    today: str | None = None,
) -> dict[str, str]:
    """Build an email-style digest (subject + body) from an alert report.

    No email is sent. The body preserves the markdown alert report and prepends a
    short diligence-only header note.

    ``today`` is accepted for deterministic output in tests; when omitted the
    current UTC-naive local date is used in ISO ``YYYY-MM-DD`` form.
    """
    stamp = today or _date.today().isoformat()
    subject = f"{subject_prefix} digest — {stamp}"
    body = f"{HEADER_NOTE}\n\n{report_text}"
    return {"subject": subject, "body": body}
